myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views



urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('shop.urls')),

    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 
       'main'}, name='auth_logout'),
    url(r'^users/', include('registration.backends.simple.urls',
       namespace='users')),
]

shop/urls.py
from django.conf.urls import url
from . import views
from myshop.settings import MEDIA_ROOT, DEBUG
from django.conf.urls.static import static
from django.conf import settings
from shop.views import FlowerDelete




urlpatterns = [

    url(r'^$', views.main_page, name='main'),
    url(r'^pro_mene/', views.about_me, name='about'),
    url(r'^kontakty', views.contacts, name='contacts'),
    url(r'^koshyk', views.basket, name='basket'),
    url(r'^samovlenya', views.orders, name='orders'),

    url(r'^flower/(?P<pk>\d+)/one/', views.one_flower, name='one_flower'),

    url(r'^kupyty/', views.main_page, name='buy'),
    url(r'^oformlenya_zamovlenya/', views.order_confirm, name='order_confirm'),

    url(r'^dodaty_kvitku', views.flower_add, name='flower_add'),
    url(r'^redahuvaty/(?P<pk>\d+)/kvitku', views.flower_edit, name='flower_edit'),
    url(r'^vydalyty/(?P<pk>\d+)/kvitku', FlowerDelete.as_view(), name='flower_del'),

    url(r'^order/(?P<pk>\d+)/one/', views.one_order, name='one_order'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Flower(models.Model):

	class Meta(object):
		verbose_name = u'Квітка'
		verbose_name_plural = u'Квіти'

	title = models.CharField(
      max_length=256,
      blank=False)
	lat_title = models.CharField(
      max_length=256,
      blank=False)
	price = models.CharField(
      max_length=256,
      blank=False)
	description = models.TextField(
      blank=False)
	photo_main = models.ImageField(
      blank=False,
      null=False)
	photo_big = models.ImageField(
      blank=True,
      null=True)
	def __unicode__(self):
		return u'%s' % (self.title)





class Order(models.Model):

	class Meta(object):
		verbose_name = u'Замовлення'
		verbose_name_plural = u'Замовлення'

	name = models.CharField(
      max_length=256,
      blank=False)
	number = models.CharField(
      max_length=256,
      blank=False)
	syma = models.CharField(
      max_length=256,
      blank=False)
	body = models.TextField(
      blank=True)
	notes = models.TextField(
      blank=True)
	def __unicode__(self):
		return u'%s' % (self.name)
    
      

shop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Flower
from .models import Order
from .util import basket_list
from .util import flow_count_name
from .util import suma
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import UpdateView, CreateView, ListView, DeleteView
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Submit, Button
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from time import time
from .util import is_digit
from datetime import datetime







###########################################################################
def main_page(request):
	flowers = Flower.objects.all()
	fl_count = flow_count_name(request)
	count = len(basket_list(request))
	return render(request, 'shop/main.html', {'flowers':flowers, 'count': count,
   'fl_count': fl_count})


#####################################################################
def about_me(request):
	return render(request, 'shop/about.html', {})


####################################################################
def contacts(request):
	return render(request, 'shop/contacts.html', {})








####################################################################
def basket(request):
   flowers = basket_list(request)
   price_list = suma(request)
   return render(request, 'shop/basket.html', locals())







################################################################

#order_confirm


def order_confirm(request):
  if request.method == "POST":
    if request.POST.get('add_button') is not None:
      errors = {}
      data = {}
      body = request.POST.get('body', '').strip()
      data['body'] = body
      syma = suma(request)
      data['syma'] = syma
      name = request.POST.get('name', '').strip()
      if not name:
        errors['name'] = u"Ведіть імя!"
      else:
        data['name'] = name
      number = request.POST.get('number', '').strip()
      if not number:
        errors['number'] = u"Ведіть номер!"
      else:
        data['number'] = number
      
           
      if not errors:
        order = Order(**data)
        order.save()
        return HttpResponseRedirect( u'%s?status_message=Замовлення успішно сформовано!'  % reverse('main'))
      else:
        return render(request, 'shop/order_confirm.html',
        {'flowers':basket_list(request), 'price_list': suma(request),'errors': errors})
    elif request.POST.get('cancel_button') is not None:
      return HttpResponseRedirect( u'%s?status_message=Формування замовлення скасовано!' % reverse('main'))
  else:
   return render(request, 'shop/order_confirm.html',
     {'flowers':basket_list(request), 'price_list': suma(request)})







#####################################################################
def one_flower(request, pk):
  flower = Flower.objects.filter(pk=pk)
  fl_count = flow_count_name(request)
  count = len(basket_list(request))
  return render(request, 'shop/one_flower.html', {'flower':flower, 'count': count, 'fl_count': fl_count})









######################################################################
@login_required
def orders(request):
  orders = Order.objects.all()
  return render(request, 'shop/orders.html', {'orders': orders})




#########################################################################
#flower_add

def flower_add(request):
  # was form posted?
  if request.method == "POST":
    # was form add button clicked?
    if request.POST.get('add_button') is not None:
      # errors collection
      errors = {}
      # data for student object
      data = {}
      # validate user input
      title = request.POST.get('title', '').strip()
      if not title:
        errors['title'] = u"Ім'я є обов'язковим"
      else:
        data['title'] = title

      data['lat_title'] = time()
        
        
      price = request.POST.get('price', '').strip()
      if not price:
          errors['price'] = u"Ціна є обов'язковою"
      else:
          if is_digit(price) == 1:
            data['price'] = price
          else:
            errors['price'] = u"Введіть ціле число!"
      description = request.POST.get('description', '').strip()
      if not description:
        errors['description'] = u"Опис є обов'язковим"
      else:
        data['description'] = description  
      photo_main = request.FILES.get('photo_main')
      if not photo_main:
        errors['photo_main'] = u"Одне фото є обов'язковим"
      else:
        data['photo_main'] = photo_main 
      photo_big = request.FILES.get('photo_big')
      if photo_big:
        data['photo_big'] = photo_big 

           
      # save flovwer
      if not errors:
        flower = Flower(**data)
        flower.save()
        # redirect to students list
        return HttpResponseRedirect( u'%s?status_message=Квітку успішно додано!'  % reverse('main'))
      else:
        # render form with errors and previous user input
        return render(request, 'shop/flower_add.html',
        {'errors': errors})
    elif request.POST.get('cancel_button') is not None:
      # redirect to home page on cancel button
      return HttpResponseRedirect( u'%s?status_message=Додавання квітки скасовано!' % reverse('main'))
  else:
   # initial form render
   return render(request, 'shop/flower_add.html', {})




#####################################################################
#flower_edit


def flower_edit(request, pk):
    flower = Flower.objects.filter(pk=pk)

    
    if request.method == "POST":
        data = Flower.objects.get(pk=pk)
        if request.POST.get('add_button') is not None:
            
            errors = {}

            title = request.POST.get('title', '').strip()
            if not title:
                errors['title'] = u"Імʼя є обовʼязковим."
            else:
                data.title = title

            data.lat_title = time()

            price = request.POST.get('price', '').strip()
            if not price:
               errors['price'] = u"Ціна є обов'язковою"
            else:
               if is_digit(price) == 1:
                 data.price = price 
               else:
                 errors['price'] = u"Введіть ціле число!"

            description = request.POST.get('description', '').strip()
            if not description:
               errors['description'] = u"Опис є обов'язковим"
            else:
               data.description = description
            photo_main = request.FILES.get('photo_main')
            if not photo_main:
                errors['photo_main'] = u"Одне фото є обов'язковим"
            else:
                data.photo_main = photo_main 
            photo_big = request.FILES.get('photo_big')
            if photo_big:
               data.photo_big = photo_big 


            if errors:
                return render(request, 'shop/flower_edit.html', {'pk': pk, 'flower': data, 'errors': errors})
            else:
                data.save()
                return HttpResponseRedirect(u'%s?status_message=Редагування квітки  завершено' % reverse('main'))
        elif request.POST.get('cancel_button') is not None:

            return HttpResponseRedirect(u'%s?status_message=Редагування квітки скасовано!' % reverse('main'))
        
    else:
        return render(request,
                      'shop/flower_edit.html', {'pk': pk, 'flower': flower[0]})
                      
                      
                    






########################################

#flower delete

class FlowerDelete(DeleteView):
  model = Flower
  template_name = 'shop/flower_delete.html'
  def get_success_url(self):
    return u'%s?status_message=Квітку успішно видалено!' % reverse('main')
  def post(self, request, *args, **kwargs):
    if request.POST.get('no_delete_button'):
      return HttpResponseRedirect(u'%s?status_message=Видалення  квітки відмінено!'% reverse('main'))
    else:
      return super(FlowerDelete, self).post(request, *args, **kwargs)
  @method_decorator(login_required)
  def dispatch(self, *args, **kwargs):
        return super(FlowerDelete, self).dispatch(*args, **kwargs)




###############################################################################

def one_order(request, pk):
  order = Order.objects.filter(pk=pk)
  return render(request, 'shop/one_order.html', {'order':order})

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}


 

{% endblock content %}


    




    

shop/templates/shop/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang='uk'>
  <head>
  	<meta charset='UTF-8'/>
    <title>Квітка</title>
  	<meta name='description'
      value='Про квіти' />
      <!-- Include Styles -->
      <link rel='stylesheet' href='https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css'>
      <link rel="stylesheet" href='{% static 'css/my.css' %}'>
      {% block extra_css %}{% endblock extra_css %}
  </head>
  <body class="body">

<div id='registration'>
{% if user.is_authenticated %}
 {{ user.username }} |
   <a href='{% url 'users:auth_logout' %}'>Вийти</a>
{% else %}
   <a href='{% url 'users:auth_login' %}'>Ввійти</a>
{% endif %}
</div>

  	<!-- Logo -->
  	<div class="row">
    <div class='col-xs-6 col-xs-offset-3'>
      <h1 id='title'>{% block title %}{% endblock title %}</h1>



    </div>
    </div>

    <!-- Start SubHeader -->
    <div class='row' id='sub-header'>
      <div class='col-xs-6 col-xs-offset-3'>
       <ul class='nav nav-pills' role='tablist'>
        <li role='presentation' {% if request.path == '/' %}class="active"{% endif %}><a href='{% url 'main' %}'>Саджанці та насіння</a></li>
        <li role='presentation' {% if '/pro_mene' in request.path %}class="active"{% endif %}><a href='{% url 'about' %}'>Про мене</a></li>
        <li role='presentation' {% if '/kontakty' in request.path %}class="active"{% endif %}><a href='{% url 'contacts' %}'>Контакти</a></li>
        <li role='presentation' {% if '/koshyk' in request.path %}class="active"{% endif %}><a href='{% url 'order_confirm' %}'>Замовити</a></li>
        {% if user.is_authenticated %}
        <li role='presentation' {% if '/samovlenya' in request.path %}class="active"{% endif %}><a href='{% url 'orders' %}'>готові замовлення</a></li>
        {% endif %}
       </ul>
      </div>
    </div>
    <!-- End SubHeader -->

     <div>
    
    {% block content %}{% endblock content %}

    

    <!-- Modal Boilerplate -->
   <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
     <div class="modal-dialog">
     <div class="modal-content">
     <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal"
      aria-label="Close">
     <span aria-hidden="true">&times;</span></button>
     

     </div>
     <div class="modal-body"><!-- --></div>
     <div class="modal-footer"><!-- --></div>
     </div>
     </div>
   </div>

  </div>

  	<!-- Start Footer -->
    <div class="row">
      <footer>&copy; 2017 Oleh Smolynets</footer>
      </div>
        
<!-- End Footer -->
  	<!-- Javascripts Section -->
  	<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js'></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.5.1/jquery.form.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
  	<script src='https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js'></script>
    <script src="{% static "js/main.js" %}"></script>
  </body>
<html>

shop/templates/shop/basket.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}
{% if flowers %}




<form action="{% url "basket" %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal" id='myform'>

{% csrf_token %}

<h2 id='basket_title'>В кошику</h2>



<div>
 <table class="table">

  <thead>
   <tr>
    <th>Назва</th>
    <th>Ціна</th>
   </tr>
  </thead>

  <tbody>
  {% for fl in flowers %}
  <tr>
   <td>{{ fl.title }}</td>
   <td>{{ fl.price }} грн</td>
   </tr>
  {% endfor %}
  </tbody>
 </table>
 </div>
 
<div id='basket_button'>
 <a href='{% url 'main' %}' class="btn btn-link">повернутись</a>
 <a href='{% url 'order_confirm' %}' class="btn btn-link">замовити</a>
</div>

</form>



{% else %}
 <div class="alert alert-warning">
 Ви не вибрали жодного товару
 </div>

 {% endif %}


 

{% endblock content %}


    




    

shop/templates/shop/contacts.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}


 

{% endblock content %}


    




    

shop/templates/shop/flower_add.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{% endblock meta_title %}
{% block title %}Додавання квітки{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
Будь-ласка, виправте наступні помилки
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<div class="add_form">





<form action="{% url "flower_add" %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal form-add_edit">
{% csrf_token %}

<div class="form-group {% if errors.title %}has-error{% endif%}">
  <label for="title" class="col-sm-2 control-label">Назва*</label>
  <div class="col-sm-10">
    <input type="text" value="{{ request.POST.title }}"
    name="title" id="title" class="form-control" />
     <span class="help-block">{{ errors.title }}</span>
  </div>
</div>

<div class="form-group {% if errors.price %}has-error{% endif%}">
  <label for="price" class="col-sm-2 control-label">Ціна*(тільки цифри!)</label>
  <div class="col-sm-10">
   <input type="text" value="{{ request.POST.price }}"
    name="price" id="price" class="form-control" />
  <span class="help-block">{{ errors.price }}</span>
  </div>
</div>

<div class="form-group {% if errors.description %}has-error{% endif %}">
    <label for="description" class="col-sm-2 control-label">Опис*</label>
    <div class="col-sm-10">
      <textarea name="description" id="description" class="form-control">{{ request.POST.description }}</textarea>
      <span class="help-block">{{ errors.description }}</span>
    </div>
  </div>

<div class="form-group {% if errors.photo_main %}has-error{% endif %}">
    <label for="photo"class="col-sm-2 control-label">Фото головне*</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_main" id="photo_main"
             class="form-control" />
      <span class="help-block">{{ errors.photo_main }}</span>
    </div>
  </div>


<div class="form-group {% if errors.photo_big %}has-error{% endif %}">
    <label for="photo_big"class="col-sm-2 control-label">Фото 2</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_big" id="photo_big"
             class="form-control" />
      <span class="help-block">{{ errors.photo_big }}</span>
    </div>
  </div>

<div class="form-group">
  <label class="col-sm-2 control-label"></label>
  <div class="col-sm-10">
  <input type="submit" value="Додати" name="add_button"
    class="btn btn-primary" />
  <button type="submit" name="cancel_button"
    class="btn btn-link">Скасувати</button>
  </div>
  </div>
</form>





<p>Поля, позначені  зірочкою,  обовязкові  для  заповнення!</p>
</div>
{% endblock content %}

shop/templates/shop/flower_delete.html
{% extends "shop/base.html" %}
{% load static from staticfiles %}
{% block meta_title %}Видалення квітки{% endblock meta_title %}
{% block title %}Видалити квітку{% endblock title %}
{% block content %}
<div id='del_confirm'>
<form action="" method="post">
{% csrf_token %}
<p>Ви дійсно хочете видалити квітку "{{ object }}"?</p>
<input type="submit" value="Так" name="delete_button"
class="btn btn-danger" />
<input type="submit" value="Ні" name="no_delete_button"
class="btn btn-danger" /><br /><br />
</form>
</div>
{% endblock content %}

shop/templates/shop/flower_edit.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{% endblock meta_title %}
{% block title %}Редагування квітки{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
Будь-ласка, виправте наступні помилки
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<div class="add_form">





<form action="{% url "flower_edit" pk %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal form-add_edit">
{% csrf_token %}

<div class="form-group {% if errors.title %}has-error{% endif%}">
  <label for="title" class="col-sm-2 control-label">Назва*</label>
  <div class="col-sm-10">
    <input type="text" value="{{ flower.title }}"
    name="title" id="title" class="form-control" />
     <span class="help-block">{{ errors.title }}</span>
  </div>
</div>

<div class="form-group {% if errors.price %}has-error{% endif%}">
  <label for="price" class="col-sm-2 control-label">Ціна*(тільки цифри!)</label>
  <div class="col-sm-10">
   <input type="text" value="{{ flower.price }}"
    name="price" id="price" class="form-control" />
  <span class="help-block">{{ errors.price }}</span>
  </div>
</div>

<div class="form-group {% if errors.description %}has-error{% endif %}">
    <label for="description" class="col-sm-2 control-label">Опис</label>
    <div class="col-sm-10">
      <textarea name="description" id="description" class="form-control">{{ flower.description }}</textarea>
      <span class="help-block">{{ errors.description }}</span>
    </div>
  </div>

<div class="form-group {% if errors.photo_main %}has-error{% endif %}">
    <label for="photo"class="col-sm-2 control-label">Фото головне</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_main" id="photo_main"
             class="form-control" />
      <span class="help-block">{{ errors.photo_main }}</span>
    </div>
  </div>


<div class="form-group {% if errors.photo_big %}has-error{% endif %}">
    <label for="photo_big"class="col-sm-2 control-label">Фото 2</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photo_big" id="photo_big"
             class="form-control" />
      <span class="help-block">{{ errors.photo_big }}</span>
    </div>
  </div>

<div class="form-group">
  <label class="col-sm-2 control-label"></label>
  <div class="col-sm-10">
  <input type="submit" value="Зберегти" name="add_button"
    class="btn btn-primary" />
  <button type="submit" name="cancel_button"
    class="btn btn-link">Скасувати</button>
  </div>
  </div>
</form>





<p>Поля, позначені  зірочкою,  обовязкові  для  заповнення!</p>
</div>
{% endblock content %}

shop/templates/shop/main.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>

    {% block content %}
    {% if request.GET.status_message %}
          <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
    {% else %}
    <div class="alert alert-warning">
       {% if buy_status %}
       В кошику {{count}} {{ fl_count }}. <a href='{% url "basket" %}' class="buy_ajax">Переглянути їх?</a>
      {% else %}
      Для замовлення будь-ласка натисніть на кнопку "купити", а після цього перейдіть в закладку "кошик", де зможити оформити замовлення!
      {% endif %}
    {% endif %}
</div>

{% if user.is_authenticated %}
<a class='btn btn-primary btn1' href='{% url "flower_add" %}'>додати квітку</a>
{% endif %}


    <!-- Start Listing -->
    <div class='row col-xs-10 col-xs-offset-1'>

      {% for fl in flowers %}

      <div class="col-md-3 lot">
                <div class="thumbnail">
                <div class="title_lot"><h4>{{ fl.title }}</h4></div>
                    <img src="{{ fl.photo_main.url }}" alt="">
                    <div class="caption">
                        <div id='price_buy'>{{ fl.price }} грн
            <button class='to_basket' value='{{ fl.lat_title }}'>Купити</button></div>
            <div id='reade_more'><a href="{% url "one_flower" fl.id %}">Читати більше...</a></div>
                    </div>
                </div>
            </div>
      {% endfor %}


    </div>
    {% endblock content %}

shop/templates/shop/one_flower.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}

<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


    {% block content %}
    <div class="alert alert-warning">
    {% if buy_status %}
       В кошику {{count}} {{ fl_count }}. Ви можете ще обрати квіти або перейти в <a href='{% url "basket" %}'>кошик</a> для замовлення!
      {% else %}
      Для замовлення будь-ласка натисніть на кнопку "купити", а після цього перейдіть в закладку "кошик", де зможити оформити замовлення!
      {% endif %}
      </div>

    <!-- Start Main Page Content-->
    <div class="buy">

    </div>
    <div class="aticle">
    {% for fl in flower %}
    <button class='to_basket bb' value='{{ fl.lat_title }}'>Купити</button></div>
    <div>
      <div class="title_lot_one"><h1>{{ fl.title }}</h1></div>
      <p id="text_about">{{ fl.description }}</p>
          <center>
      <img src='{{ fl.photo_main.url }}' width='350' height='250' class="big_photo img-thumbnail" id='big_photo'>
          </center>
          <center>
      {% if fl.photo_big %}
        <img src='{{ fl.photo_big.url }}' width='350' height='250' class="big_photo img-thumbnail" id='big_photo'>
      {% endif %}
        </center>
      </div>
      {% if user.is_authenticated %}
      <div class="reg_del_button">
    <a class='btn btn-primary' href='{% url 'flower_edit' fl.id %}'>редагувати</a>
    <a class='btn btn-primary' id='del_buttom' href='{% url 'flower_del' fl.id %}'>видалити</a>
    </div>
    {% endif %}
    {% endfor %}
    </div>
    {% endblock content %}

shop/templates/shop/one_order.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}

<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}
    
{% for order in order %}
 <div id='one_order'>

  <div class="ord_one_col">{{ order.name }}</div>
  <div class="ord_one_col">{{ order.number }}</div>
  <div class="ord_one_col">{{ order.body }}</div>
  <div class="ord_one_col">{{ order.syma }}</div>
  <div class="ord_one_col">{{ order.notes }}</div>

 </div>
{% endfor %}

{% endblock content %}
    




  	
  	

shop/templates/shop/order_confirm.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>


{% block content %}


{% if flowers %}
<div class='row'>
<div id='form_confirm'>
<form action="{% url "order_confirm" %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal">

{% csrf_token %}

<h2 id='confirm_title'>Оформлення замовлення</h2>



<div id='basket_details'>
<div class="row">
  <div class="col-sm-2">Назва</div>
  <div class="col-sm-2 price_title">Ціна</div>
</div>
{% for fl in flowers %}
<div class="one_confirm">
<div class="row">
  <div class="col-sm-2">{{ fl.title }}</div>
  <div class="col-sm-3 one_price">{{ fl.price }} грн</div>
  <div><button class='from_basket' value='{{ fl.lat_title }}'>Видалити
  </button>
  </div>
</div>
</div>
{% endfor %}
<div id='suma_form'>
<div class="row">
Сума замовлення  {{price_list}} грн
</div>
</div>
</div>



<div class="form-group">
  <label class="col-sm-2 control-label">Імя*</label>
  <div class="col-sm-10">
    <input type="text" value="{{ request.POST.name }}"
      name="name" class="form-control" />
      <span class="help-block">{{ errors.name }}</span>
  </div>
</div>



<div class="form-group">
  <label class="col-sm-2 control-label">номер телефону*</label>
  <div class="col-sm-10">
    <input type="text" value="{{ request.POST.number }}"
      name="number" class="form-control" />
      <span class="help-block">{{ errors.number }}</span>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-2 control-label">Додаткові нотатки</label>
  <div class="col-sm-10">
    <textarea name="notes" id="notes" class="form-control"></textarea>
  </div>
</div>

<div class="form-group">
  <label class="col-sm-2 control-label"></label>
  <div class="col-sm-10">
    <textarea type="text" value=""
      name="body" class="form-control sr-only" readonly>{% for fl in flowers %}
      {{ fl.title }}  {{ fl.price }}грн;
      {% endfor %}</textarea
  </div>
</div>

</div>


<div class="row">
 <label class="col-sm-2 control-label"></label>
 <div class="col-sm-10">
   <input type="submit" value="замовити" name="add_button"
     class="btn btn-primary from_basket"
     {% if errors %}
     {% else %}
     class='from_basket'
     {% endif %}
      />
   <button type="submit" name="cancel_button"
     class="btn btn-link">Скасувати</button>
 </div>
</div>
 
</div>
</form>
</div>


{% else %}
 <div class="alert alert-warning">
 Ви не вибрали жодного товару. Будь-ласка, поверніться на <a href='{% url 'main' %}' class="btn btn-link">головну сторінку</a> і виберіть хоча б одну квітку!
 </div>
 {% endif %}

{% endblock content %}


    




    

shop/templates/shop/orders.html
{% extends 'shop/base.html' %}
{% load static from staticfiles %}



<title>{% block title %}Купівля насіння та саджанців квітів{% endblock title %}</title>

    {% block content %}
    

      
<table class="table">

 <tr>
 <th>
  #
 </th>
 <th>
  імя
 </th>
 <th>
  телефон
 </th>
 <th>
  замовлення
 </th>
 <th>
  сума
 </th>
 </tr>
 </thead>

<tbody>

{% for order in orders %}
 <tr>

  <td><a href='{% url 'one_order' order.id %}'>{{ forloop.counter }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.name }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.number }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.body }}</td>
  <td><a href='{% url 'one_order' order.id %}'>{{ order.syma }}</td>

 </tr>
{% endfor %}

</tbody>
</table>



    {% endblock content %}


    




    